import dotenv from 'dotenv';
import mongoose from 'mongoose';
import Product from '../models/Product.js';
import { randomUUID } from 'crypto';
import { mkdir, writeFile } from 'fs/promises';
import path from 'path';
import sharp from 'sharp';

dotenv.config({ path: path.resolve(process.cwd(), './.env') });

const uploadsDir = path.resolve(process.cwd(), './server/uploads');

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function svgFor(name, color) {
  const safe = name.replace(/&/g, '&amp;');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns='http://www.w3.org/2000/svg' width='1200' height='800' viewBox='0 0 1200 800'>\n  <rect width='100%' height='100%' fill='${color}'/>\n  <g fill='white' font-family='Helvetica, Arial, sans-serif'>\n    <text x='6%' y='45%' font-size='48' font-weight='700'>${safe}</text>\n    <text x='6%' y='60%' font-size='22'>DevGear autogenerated product image</text>\n  </g>\n</svg>`;
}

async function ensureUploads() {
  await mkdir(uploadsDir, { recursive: true });
}

async function generateImageFiles(name) {
  const id = randomUUID();
  const svg = svgFor(name, `hsl(${Math.floor(Math.random() * 360)} 60% 30%)`);
  const svgBuffer = Buffer.from(svg, 'utf8');
  const svgFilename = `${id}.svg`;
  const svgPath = path.join(uploadsDir, svgFilename);
  await writeFile(svgPath, svgBuffer);

  const sizes = [400, 800, 1200];
  const variants = {};

  for (const w of sizes) {
    const outJpg = `${id}-${w}.jpg`;
    const outWebp = `${id}-${w}.webp`;
    const outJpgPath = path.join(uploadsDir, outJpg);
    const outWebpPath = path.join(uploadsDir, outWebp);

    await sharp(svgBuffer).resize({ width: w }).jpeg({ quality: 80 }).toFile(outJpgPath);
    await sharp(svgBuffer).resize({ width: w }).webp({ quality: 75 }).toFile(outWebpPath);

    variants[w] = {
      jpg: `http://localhost:5000/uploads/${outJpg}`,
      webp: `http://localhost:5000/uploads/${outWebp}`
    };
  }

  // choose the largest jpg as main url
  const mainUrl = `http://localhost:5000/uploads/${id}-1200.jpg`;
  return { url: mainUrl, alt: `${name} (autogen)`, variants };
}

async function main() {
  if (!process.env.MONGODB_URI) {
    console.error('MONGODB_URI not set in server/.env');
    process.exit(1);
  }

  await ensureUploads();

  await mongoose.connect(process.env.MONGODB_URI, { dbName: process.env.MONGODB_DB || undefined });

  const categories = ['Keyboards', 'Monitors', 'Audio', 'Accessories', 'Storage', 'Laptops'];
  const created = [];

  for (let i = 1; i <= 30; i++) {
    const name = `DevGear Prod ${i}`;
    const slug = slugify(name);
    const sku = `DG-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
    const category = categories[i % categories.length];
    const price = Math.floor(999 + Math.random() * 49990);
    const stock = Math.floor(5 + Math.random() * 95);
    const image = await generateImageFiles(name);

    const product = {
      name,
      slug: `${slug}-${i}`,
      sku,
      description: `Auto-generated product ${i} for DevGear demo.`,
      category,
      brand: 'DevGear Autogen',
      price,
      compareAtPrice: null,
      stock,
      images: [image],
      tags: ['autogen', category.toLowerCase()],
      specs: { warranty: '1 year', color: 'black' }
    };

    try {
      const doc = await Product.create(product);
      created.push(doc);
      console.log('Created', doc._id.toString(), product.name);
    } catch (err) {
      console.error('Failed to create product', err.message || err);
    }
  }

  console.log('Created', created.length, 'products');
  await mongoose.disconnect();
}

main().catch((err) => {
  console.error(err);
  process.exit(2);
});
